-- Openflow Financial Services Workshop - Teardown
-- Run this script to drop all workshop objects from the NASDAQ_DEMO database.

USE ROLE ACCOUNTADMIN;
USE DATABASE NASDAQ_DEMO;

-- Phase 5: Cortex Agent
DROP AGENT IF EXISTS NASDAQ_AGENT;

-- Phase 4: Cortex AI
DROP CORTEX SEARCH SERVICE IF EXISTS EARNINGS_REPORTS_SEARCH;
DROP SEMANTIC VIEW IF EXISTS HISTORICAL_QUOTES_SEMANTIC_VIEW;
DROP TABLE IF EXISTS EARNINGS_REPORTS_CHUNKS;
DROP TABLE IF EXISTS EARNINGS_REPORTS_PARSED;
REMOVE @EARNINGS_REPORTS_STAGE;
DROP STAGE IF EXISTS EARNINGS_REPORTS_STAGE;

-- Phase 2: Structured Data
DROP DYNAMIC TABLE IF EXISTS HISTORICAL_QUOTES_TYPED;
DROP VIEW IF EXISTS HISTORICAL_QUOTES_TIMESERIES;
DROP TABLE IF EXISTS HISTORICAL_QUOTES_FORECAST;
TRUNCATE TABLE IF EXISTS HISTORICAL_STOCK_QUOTES;
