-- Snowflake setup for the Openflow Financial Services Workshop.
-- Creates the NASDAQ_DEMO database, stage, and grants required by Openflow.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS NASDAQ_DEMO;
USE DATABASE NASDAQ_DEMO;

CREATE OR REPLACE STAGE EARNINGS_REPORTS_STAGE
    ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = ( ENABLE = TRUE );

GRANT READ ON STAGE EARNINGS_REPORTS_STAGE TO ROLE OPENFLOW_RUNTIME_ROLE;
GRANT WRITE ON STAGE EARNINGS_REPORTS_STAGE TO ROLE OPENFLOW_RUNTIME_ROLE;
